uwsgi:
  image: "chriscircleci/info-tech-one-dot-oh-uwsgi:${CIRCLE_SHA1}"
nginx:
  image: "chriscircleci/info-tech-one-dot-oh-nginx:${CIRCLE_SHA1}"
  links:
    - uwsgi
  ports:
    - "${NGINX_PORT}"
