uwsgi:
  image: "veerendradevops/circleci-uwsgi:d2f60f9a9b76a8eb3c48b541566ae63dd8a3be83"
nginx:
  image: "veerendradevops/circleci-nginx:d2f60f9a9b76a8eb3c48b541566ae63dd8a3be83"
  links:
    - uwsgi
  ports:
    - "1234:1234"
